data_to_replicate:
- base_table: matdoc
  load_frequency: '@hourly'
- base_table: ckmlhd
  load_frequency: '@daily'
- base_table: ckmlcr
  load_frequency: '@daily'
- base_table: makt
  load_frequency: '@daily'
  cluster_details:
    columns:
    - spras
- base_table: mara
  load_frequency: '@daily'
- base_table: marc
  load_frequency: '@hourly'
- base_table: mard
  load_frequency: '@hourly'
- base_table: t001
  load_frequency: '@once'
- base_table: t001k
  load_frequency: '@once'
- base_table: t001l
  load_frequency: '@once'
- base_table: t001w
  load_frequency: '@once'
- base_table: t002
  load_frequency: '@once'
- base_table: t009
  load_frequency: '@once'
- base_table: t009b
  load_frequency: '@once'
- base_table: t023
  load_frequency: '@once'
- base_table: t023t
  load_frequency: '@once'
- base_table: t134
  load_frequency: '@once'
- base_table: t134t
  load_frequency: '@once'
- base_table: t148t
  load_frequency: '@once'
- base_table: t156t
  load_frequency: '@once'
- base_table: t157e
  load_frequency: '@once'
- base_table: t179
  load_frequency: '@once'
- base_table: t179t
  load_frequency: '@once'
- base_table: tcurc
  load_frequency: '@once'
- base_table: tcurf
  load_frequency: '@once'
- base_table: tcurr
  load_frequency: '@daily'
- base_table: tcurt
  load_frequency: '@daily'
- base_table: tcurx
  load_frequency: '@daily'
- base_table: mch1
  load_frequency: '@daily'
- base_table: mska
  load_frequency: '@weekly'
- base_table: mslb
  load_frequency: '@weekly'
- base_table: msku
  load_frequency: '@weekly'
- base_table: mkol
  load_frequency: '@weekly'
